import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Delta  - المعهد العالي للحاسبات وتكنولوجيا المعلومات بطلخا ",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // تأكد أن ملف logo.png موجود داخل فولدر public مباشرة
    apple: "/logo.png", // اختياري: لأجهزة الآيفون والـ Apple devices
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
